# Generated by Django 4.0.5 on 2022-06-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='slug',
        ),
    ]
