# Generated by Django 4.0.5 on 2022-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_todo_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
